---
base_dir: data/model

data:
  batch_size: 16
  dataset_dir: CRIME-SH/8
  test_batch_size: 8
  val_batch_size: 8
  graph_pkl_filename: graph/adj_mx_sh.pkl

model:
  cl_decay_steps: 2000
  filter_type: dual_random_walk
  horizon: 1
  input_dim: 8
  l1_decay: 0
  max_diffusion_step: 2
  num_nodes: 16
  num_rnn_layers: 2
  output_dim: 8
  rnn_units: 64
  seq_len: 9
  use_curriculum_learning: true

train:
  base_lr: 0.0001
  dropout: 0.3
  epoch: 0
  epochs: 100
  epsilon: 1.0e-3
  global_step: 0
  lr_decay_ratio: 0.1
  max_grad_norm: 5
  max_to_keep: 100
  min_learning_rate: 2.0e-06
  optimizer: adam
  patience: 50
  steps: [20, 30, 40, 50]
  test_every_n_epochs: 10
